force-app/main/default/objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assignments</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assignment__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Descriptions of the assignments</description>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <description>Due date of the Assignments</description>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the assignments</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Name of the Assignments</description>
    <label>Title</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/assignmentClassTest.cls
@isTest
public class assignmentClassTest {
    static testMethod void getAssigmentRecordListTest(){
        Test.startTest();
        assignmentClass.getAssigmentRecordList();
        Test.StopTest();
    }
    static testMethod void updateCreateAssigmentRecordTest(){
        assignmentClass.AssignmentFields fields= new assignmentClass.AssignmentFields();  
        fields.title='test title';
        fields.status='Completed';
        
         assignmentClass.AssignmentFields fields2= new assignmentClass.AssignmentFields();  
        fields2.title='test title2';
        fields2.dueDate=system.today();
        fields2.status='Completed';
        Test.startTest();
        assignmentClass.updateCreateAssigmentRecord(fields);
         assignmentClass.updateCreateAssigmentRecord(fields2);

        Test.StopTest();
    }
    @testSetUp static void setUp(){
    Assignment__c assignObj = new Assignment__c();
            assignObj.Title__c = 'test title';
            assignObj.Description__c = 'test title description';
            assignObj.Due_Date__c = system.today();
            assignObj.Status__c = 'Not Started';
            insert assignObj;     
    }
    
}