force-app/main/default/objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assignments</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assignment__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Descriptions of the assignments</description>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <description>Due date of the Assignments</description>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the assignments</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Name of the Assignments</description>
    <label>Title</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/assignmentClass.cls
public  class assignmentClass {
/****************************************************************
 * Method Name : getAssigmentRecordList
 * Description : This method is used to return the list of Assignment Records.
***************************************************************/
	 @AuraEnabled(cacheable=true)
    public static List<Assignment__c> getAssigmentRecordList(){
        List<Assignment__c> assigmentList = [Select Id,Title__c,Description__c,Due_Date__c,Status__c FROM Assignment__c];
        
        return assigmentList;
    }
    @AuraEnabled()
    public static  string updateCreateAssigmentRecord(AssignmentFields record){
        String response;
        List<Assignment__c> assigmentList = [Select Id,Title__c,Description__c,Due_Date__c,Status__c FROM Assignment__c 
                                             WHERE Title__c =: record.title LIMIT 1];
        if(assigmentList.size()!=0){
            
            Assignment__c assignObj = new Assignment__c(Id= assigmentList.get(0).Id);
            if(assigmentList.get(0).Description__c != record.description && record.description !=''){
                assignObj.Description__c = record.description;
            }
            if(assigmentList.get(0).Due_Date__c != record.dueDate && record.dueDate != Null){
                assignObj.Due_Date__c = record.dueDate;
            }
            if(assigmentList.get(0).Status__c != record.status && record.status !=''){
                assignObj.Status__c = record.status;
            }
            
            
            update assignObj;
            response = 'Records Updated Successfully';
        }
 		 else{
			Assignment__c assignObj = new Assignment__c();
            assignObj.Title__c = record.title;
            assignObj.Description__c = record.description;
            assignObj.Due_Date__c = record.dueDate;
            assignObj.Status__c = record.status;
            insert assignObj;
            response = 'Records Created Successfully';
        }
        return response;
    }
    
    public Class AssignmentFields{
        @AuraEnabled
        public String title {get; set;}
        @AuraEnabled
        public String description{get; set;}
        @AuraEnabled
        public Date dueDate{get; set;}
        @AuraEnabled
        public String status{get; set;}
    }
}